---
micronaut:
  application:
    name: gamification
  server:
    port: 5000
    cors:
      enabled: true

---
mongodb:
  uri: "mongodb+srv://ashismohanty:ashis_21@cluster0-iftvw.mongodb.net/test?retryWrites=true&w=majority"
datasources:
  default:
    url: jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: ''
jpa:
  default:
    packages-to-scan:
      - 'org.micronaut'
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
---
#consul:
#  client:
#    registration:
#      enabled: true
#    defaultZone: "${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}"
